spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 500
  h2:
    console:
      enabled: true
logging:
  level:
    root: INFO
    com.teamsparta.codeimprovement.domain2.course.repository: INFO
    com.teamsparta.codeimprovement.domain2.course.service: INFO
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace

auth:
  jwt:
    issuer: team.sparta.com
    secret: b5aM8dP2lR4sV1xQ0eZ6wH3gT9uC7nK5
    accessTokenExpirationHour : 1680